version: '3.8'

services:
  remittance-mcp-server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: remittance-mcp-server-dev
    ports:
      - "8080:8080"
      - "9229:9229"  # Debug port
    environment:
      # JWT Configuration
      - JWT_SECRET=${JWT_SECRET:-kX8jBUle1vefPPoGrG58ZDDU+f+l9PBJUPWoqT3xgEE=}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN:-1h}
      
      # Server Configuration
      - PORT=8080
      - NODE_ENV=development
      
      # Remittance API Configuration
      - REMITTANCE_API_BASE_URL=${REMITTANCE_API_BASE_URL:-http://localhost:8080}
      - REMITTANCE_API_TIMEOUT=${REMITTANCE_API_TIMEOUT:-30000}
      
      # Callback Configuration
      - CALLBACK_VOICE_URL=${CALLBACK_VOICE_URL:-http://localhost:8080/voice/}
      - CALLBACK_VOICE_TOKEN=${CALLBACK_VOICE_TOKEN:-yourVoiceToken}
      - CALLBACK_TEXT_URL=${CALLBACK_TEXT_URL:-http://localhost:8080/text/}
      - CALLBACK_TEXT_TOKEN=${CALLBACK_TEXT_TOKEN:-yourTextToken}
      
      # Logging
      - LOG_LEVEL=debug
    volumes:
      - .:/app
      - /app/node_modules
      - ./logs:/app/logs
    restart: unless-stopped
    command: ["npm", "run", "dev"]
    networks:
      - remittance-network

networks:
  remittance-network:
    driver: bridge
